services:
  - type: web
    name: cloudplay
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: FOXPHONE_API_KEY
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: NODE_VERSION
        value: 20
